name: openscvx
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - scipy
  - numpy
  - pyaml
  - termcolor
  - plotly
  - pip:
      - jax
      - cvxpy
      - cvxpygen
      - qoco
      - qocogen
